### ISSUE TITLE
You can unroll loops at compile time using [unroll]

### ISSUE THREAD

**Issue by TorutheRedFox** [xan1242/NFSC_CustomVT#3]
This would make the code a little more readable

**Comment by xan1242** [comment]
Good to know. I'm not very familiar with HLSL.

I wasn't really making it readable or nice (neither were the original devs, I took the unrolled code from Undercover).

**Comment by xan1242** [comment]
Check [the latest commit](https://github.com/xan1242/NFSC_CustomVT/commit/0142b4bfc349d0c398e17fc5e2fbb3b207ccfc9a), it should be good now.

**Comment by TorutheRedFox** [comment]
> Good to know. I'm not very familiar with HLSL.
> 
> I wasn't really making it readable or nice (neither were the original devs, I took the unrolled code from Undercover).

meanwhile I took the rolled loops while testing from MW ;P
